SystemOrganization addCategory: #ApplicationSecurity!
SystemOrganization addCategory: #'ApplicationSecurity-CheckPoint'!
SystemOrganization addCategory: #'ApplicationSecurity-CheckPoint-Tests'!
SystemOrganization addCategory: #'ApplicationSecurity-Core'!
SystemOrganization addCategory: #'ApplicationSecurity-Core-Tests'!
SystemOrganization addCategory: #'ApplicationSecurity-Exceptions'!
SystemOrganization addCategory: #'ApplicationSecurity-UserModel'!
